// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mmnrtmkuueqohhaddtxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1tbnJ0bWt1dWVxb2hoYWRkdHhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MjU3NjcsImV4cCI6MjA3NDQwMTc2N30.vYVzIgkdia8birnp0StgUrEKw4PZZcxcM1U4aqILfN4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});